---
title: "dbmefu_vignette"
author: "Giovanni Laudanno"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dbmefu_vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The aim of the project is to collect the data for the MeFu database.

First, load the library:

```{r}
install.packages("devtools")
devtools::install_github("Giappo/dbmefu")
library(dbmefu, quietly = TRUE)
```

First provide the database addresses

```{r}
# Address of the main database
  address1 <- "https://drive.google.com/file/d/1j7EpOrkGWiWfIj1Q6IyV-S0cqIzG90Em/"
# Address of the secondary database that you wish to integrate
  address2 <- "https://docs.google.com/spreadsheets/d/1AipazAj6Ebfuv0Kek4xMRYva8sodUQs-4AI3li0IbzY/"
```

Then you can download the databases and clean them

```{r}
df1 <- dbmefu::import_df(address1)
df2 <- dbmefu::import_df(address2)
df1 <- dbmefu::ripulisci_df(df1)
df2 <- dbmefu::ripulisci_df(df2)
```

Finally you can merge the databases with the following call

```{r}
db_merged <- dbmefu::merge_db(df1 = df1, df2 = df2)
print(db_merged)
```

You can check for example the list of all the editors in the complete database

```{r}
editors <- dbmefu::editori_unici(db_merged)
editors
```
